### ISSUE TITLE
simplify geometries of counties and rivers

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-matthew#13]
We have a large file now, where most of the size is in the fine details of the rivers and county boundaries.

**Comment by jordansread** [comment]
@ldecicco-USGS interested in this too?

**Comment by ldecicco-USGS** [comment]
Not sure I know off-hand how to do it. Might be lots-o'googlin'. So, if you know how to do it, do it. If it's still a task when I'm done with the points, I'll give it a go.

**Comment by jordansread** [comment]
ok, i will take it
