### ISSUE TITLE
map style

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-matthew#15]
we have a start on the map, but 
1) a slightly different grey for the rest of the US, so this map isn't floating
2) maybe a background so that the Ocean isn't pure white
3) define river and county classes in css

**Comment by jordansread** [comment]
@jiwalker-usgs where do you want map css to live? In the layout/css/main.css?

**Comment by jiwalker-usgs** [comment]
yeah, I don't really like the name layout anymore, but we can stick with it for now

**Comment by jordansread** [comment]
![image](https://cloud.githubusercontent.com/assets/2349007/19197349/f9f42d96-8c7e-11e6-8462-6910e1c1dd57.png)

**Comment by ldecicco-USGS** [comment]
Want more flowlines? change the streamorder to 5 in viz.yaml

**Comment by jordansread** [comment]
balancing file size w/ detail is tricky. We'll see how big that makes it
