### ISSUE TITLE
inject svg into html?

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-matthew#16]
This isn't what we have done in the past (we have used `object`), but this would make things easier, because we could use external js and css.

**Comment by jiwalker-usgs** [comment]
https://github.com/USGS-VIZLAB/vizlab/pull/78 had to be added to vizlab, everybody update in order to get this to work

**Comment by jordansread** [comment]
Looks good, but @jiwalker-usgs how to we add css to the target so it is used for the svg?
