### ISSUE TITLE
write jquery to toggle colors according to timestep

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-matthew#18]
```
$('.prcp-1-4').css("{color:blue}")
```

we are giving each county a class for each timestep:

`prcp-{timestep}-{colorbin}`
so `"prcp-1-4"` is step 1, color 4. 

Colors will come from a json file that we build w/ `toJSON` based on number of bins and the color pallete

**Comment by jiwalker-usgs** [comment]
need to add play button, but #39 should be a good start to this
