### ISSUE TITLE
bind real precip data to timesteps and color bins

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-matthew#23]
there is mocked up data in the visualize map section, which needs to be replaced w/ the actual precip data per county

**Comment by wdwatkins** [comment]
We're just going with precip in the last hour right for the color binning?

**Comment by jordansread** [comment]
yep. Not cumulative

**Comment by wdwatkins** [comment]
actual processing is handled in #25 right?  just need to insert that output here?
