### ISSUE TITLE
Discharge color data frame

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/hurricane-matthew#37]
Three columns:
site, timestamp (index....), discharge class

**Comment by wdwatkins** [comment]
lat lon too?

**Comment by ldecicco-USGS** [comment]
that would already be in the shapefile....I'm on this one, nearly done, ish

**Comment by jordansread** [comment]
is this ready to go?

**Comment by jordansread** [comment]
Looks like there are more sites in the classification than there are in the set of sites

**Comment by jordansread** [comment]
oh, more like multiple values for the same site and the same timestep
