### ISSUE TITLE
Add footer content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-matthew#54]
currently empty

**Comment by wdwatkins** [comment]
#57 fills some in

**Comment by wdwatkins** [comment]
Width fixed in #81, do we want all four other vizzes linked?

**Comment by jordansread** [comment]
@mwernimont here is what it looks like now:

![image](https://cloud.githubusercontent.com/assets/2349007/19271397/29121ea4-8f8a-11e6-9f83-2390280f09d9.png)

can you 
- [ ] remove rounded corners
- [ ] make the icons/cards smaller
- [ ] make any other style improvements you have in mind.

**Comment by eread-usgs** [comment]
done w/ #96
