### ISSUE TITLE
fix IE

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-VIZLAB/hurricane-matthew#65]
same svg issue as we've seen before

**Comment by jordansread** [comment]
- [x] use clipPath for states
- [ ] scale svg on IE like we have done before

**Comment by jordansread** [comment]
maybe as simple as this? 
https://github.com/USGS-VIZLAB/great-lakes-microplastics/pull/108/files#diff-5e218fe030373495579e5ad83d950912R2
