### ISSUE TITLE
river plot bug

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/hurricane-matthew#76]
![image](https://cloud.githubusercontent.com/assets/2349007/19242026/0962cc24-8ed7-11e6-97da-5c3b18ca0bf0.png)

I think this is from out of order vertices.

@ldecicco-USGS  up for taking a look?

**Comment by jordansread** [comment]
the diversion thing on the left. Or is that real?

**Comment by ldecicco-USGS** [comment]
I'm still trying to figure out how to put a state boundary on a map....I don't have any idea what that is.

**Comment by wdwatkins** [comment]
@jread-usgs where is that geographically?

**Comment by ldecicco-USGS** [comment]
Mississippi

**Comment by wdwatkins** [comment]
I think this is real, looks like it corresponds to the Panther Swamp Wildlife Refuge area on google maps?  Looks like there's some man-made channels
